# GitHub Action for generating a contribution graph with a snake animation.

name: Generate Snake

# Run the workflow every 6 hours
on:
  schedule:
    - cron: "0 */6 * * *"

  # Allow manual execution from GitHub Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Generate the snake animation (Updated Version)
      - name: Generate Snake
        uses: Platane/snk@v2.2.1
        id: snake-gif
        with:
          github_user_name: jhoncarlnayao
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Show Git status (Debugging step)
      - name: Show Git Status
        run: git status

      # Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Commit and push changes
      - name: Commit & Push Changes
        run: |
          git add dist/github-contribution-grid-snake.gif dist/github-contribution-grid-snake.svg
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
