# GitHub Action for generating a contribution graph with a snake animation.

name: Generate Snake

# Controls when the action will run. Runs every 6 hours.
on:
  schedule:
    - cron: "0 */6 * * *"

  # Allows running the workflow manually from the Actions tab
  workflow_dispatch:

# The sequence of jobs in this workflow:
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Generates the snake animation
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: jhoncarlnayao
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Show the status of the repository
      - name: Show Git Status
        run: git status

      # Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Commit and push the changes
      - name: Commit & Push Changes
        run: |
          git add dist/github-contribution-grid-snake.gif dist/github-contribution-grid-snake.svg
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
